apiVersion: apps/v1
kind: Deployment
metadata:
  name: appweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proyectoazuremauricio
  template:
    metadata:
      labels:
        app: proyectoazuremauricio
    spec:
      containers:
        - name: proyectoazuremauricio
          image: cloudtf458/proyectoazuremauricio:$(Build.BuildId)
          ports:
            - containerPort: 80